# SQLite version 3.x
#   gem install sqlite3
#
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: deviseOauth_development
  pool: 5
  username: root
  password:
  host: localhost
 

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: deviseOauth_test
  pool: 5
  username: root
  password:
  host: localhost
 
  
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: deviseOauth_production
  pool: 5
  username: root
  password: 
  host: localhost
 